Tiles:
    .db $E7, $EF, $E3, $EF, $EF, $EF, $FF, $A5, $FF, $81, $83, $BD, $DB, $A5, $99, $A5
    .db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    .db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $CF, $FF, $B7, $FF, $FF, $FF, $FF, $FF
    .db $FF, $FF, $FF, $FF, $FF, $FF, $E7, $FF, $DB, $FF, $BD, $FF, $FF, $FF, $FF, $FF

BG_Palette:
    .db $87, $10, $EF, $18, $55, $19, $D9, $15
    .db $45, $29, $E7, $25, $AC, $1E, $59, $2F
    .db $A5, $20, $E7, $2C, $A9, $41, $89, $5E
    .db $28, $39, $AD, $4D, $94, $62, $9B, $77
    .db $69, $28, $8D, $30, $B3, $38, $B9, $3C
    .db $6F, $24, $B5, $20, $1C, $1D, $3F, $1A
    .db $A7, $18, $CA, $1C, $31, $29, $B7, $31
